Proyecto_final/Proyecto_final/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("tienda.urls")),
    
    path('productos/', include("producto.urls")),
]

Proyecto_final/producto/urls.py
from django.urls import path

from .import views

app_name = "producto"

urlpatterns = [
   
    path('',views.index,name ="index"),
    
    #path('producto_categoria/list',views.producto_categoria_list,name ="producto_categoria_list"),
 
    path('productocategoria/list/',views.ProductoCategoriaList.as_view(),name ="productocategoria_list"),#las classes no se ejecutan de forma automatica  asi que agregamso el.as_view()
    
    path('productocategoria/create/', views.ProductoCategoriaCreate.as_view(), name="producto_categoria_create"),
    
    path('producto_categoria/detalles/<int:pk>/', views.ProductoCategoriaDetail.as_view(), name="producto_categoria_detalles"),
    path('producto_categoria/update/<int:pk>/', views.ProductoCategoriaUpdate.as_view(), name="producto_categoria_update"),
    path('producto_categoria/delete/<int:pk>/', views.ProductoCategoriaDelete.as_view(), name="producto_categoria_delete"),



]     

Proyecto_final/tienda/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from tienda import views
from .views import *
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
   
    path('',views.index,name ="index"),
    
    path('vendedor/list',views.vendedor_list,name='vendedor_list'),
    
    path('vendedor/creat',views.vendedor_creat,name='vendedor_creat'),
    
    path('eliminarVendedor/<vendedor_nombre>',views.eliminar_vendedor,name='EliminarVendedor'),
    
    
    
    path('comprador/list',views.comprador_list,name='comprador_list'),
    
    path('comprador/creat',views.comprador_creat,name='comprador_creat'),
    
    path('eliminarComprador/<comprador_nombre>',views.eliminar_comprador,name='EliminarComprador'),
    
    
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('about',about,name="about"),
    
    #crear producto
    
    path('crear_producto/',views.crear_producto,name="crear_producto"),
    
    #login , logout, registro
    
    path('login/', views.login_request, name='Login'),
    
    path('registro/', views.registro, name='Registro'),
    
    path ("logout/", LogoutView.as_view(template_name="tienda/logout.html"), name="logout"),  
   
]

Proyecto_final/producto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class ProductoCategoria(models.Model):
    
    nombre=models.CharField(max_length=30)
    descripcion=models.TextField(null=True, blank=True, verbose_name="descripción")
    
    def __str__(self)->str:
        
        return self.nombre
    class Meta:
        verbose_name="Categoría de producto"
        verbose_name_plural="Categorías de productos"
        
        
class Producto(models.Model): 
    categoria_id = models.ForeignKey(ProductoCategoria, null=True, on_delete=models.SET_NULL)
    nombre=models.CharField(max_length=100)
    unidad_medida = models.CharField(max_length=100)
    cantidad=models.FloatField()
    precio=models.FloatField()
    descripcion=models.TextField(null = True, blank = True, verbose_name="descripción")
    fecha_de_actualizacion=models.DateTimeField(null=True, blank=True, default=timezone.now, editable=False) 
    
    
    def __str__(self)->str:
        return f"{self.nombre} ({self.unidad_medida}) ${self.precio:.2f}" 
           
    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

Proyecto_final/producto/forms.py
from django import forms

from .models import *

class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = ProductoCategoria
        fields = "__all__"
        
class ProductoForm(forms.ModelForm):
    
    class Meta:
        models = Producto
        fields = "__all__"        

Proyecto_final/producto/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import *
from .models import *

def index(request):
    return render(request,"producto/index.html")

#def producto_categoria_list(request):
   # objects = ProductoCategoria.objects.all()
   # context = {"objects_list":objects}
   # return render(request,"producto/producto_categoria_list.html", context)
   
class ProductoCategoriaList(ListView):
    model = ProductoCategoria
    # context_object_name = "object_list"
    # template_name = "producto/productocategoria_list.html"
    template_name = 'producto/producto_categoria_list.html'
    
    def get_queryset(self):
        if self.request.GET.get('consulta'):
            
           consultar = self.request.GET.get('consulta')
           object_list =ProductoCategoria.objects.filter(nombre__icontains=consultar)
        else:
           object_list = ProductoCategoria.objects.all()
           
        return object_list   
       
       
class ProductoCategoriaCreate(CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm 
    success_url = reverse_lazy('producto:productocategoria_list')                                                          
    template_name = 'producto/producto_categoria_create.html'    
       
# def productocategoria_detail(request, pk: int):
#     consulta = ProductoCategoria.objects.get(id=pk)
#     return render(request, "producto/producto_categoria_detalles.html", {"object": consulta})
    
    
class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria
    template_name = 'producto/producto_categoria_detalles.html'                          
    context_object_name = 'categoria'
    
class ProductoCategoriaUpdate(UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:producto_categoria_list")
    context_object_name = 'categoria'
    template_name = 'producto/producto_categoria_create.html'
class ProductoCategoriaDelete(DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy("producto:producto_categoria_list")   
    context_object_name = 'categoria'
    template_name = 'producto/producto_categoria_confirm_delete.html'

Proyecto_final/producto/templates/producto/index.html
{% extends 'tienda/base.html' %}

{% block title  %}
    Productos
{% endblock title %}

{% block contenido %}

     <h1>Productos</h1>
     <div class="d-grid gap-3"></div>
     <a href="{% url 'producto:productocategoria_list' %}"><button class="btn btn-primary">Categorias de productos </button> </a>
     
     <a href="{% url 'producto:producto_categoria_create' %}"><button class="btn btn-primary">Crear Categorias de productos </button> </a>
{% endblock contenido %}

Proyecto_final/producto/templates/producto/producto_categoria_confirm_delete.html
{% extends 'tienda/base.html' %}

{% block title  %}
    Eliminar de Categoria de Productos
{% endblock title %}

        {% block contenido %}

            <h1>Eliminar de Categoria de Productos</h1>
            <p class="fs-5 fst-italic" > Confirma eliminar {{categoria}}</p>

            <form method="post"></form>

                     {% csrf_token %}
                        <div class="d-grid gap-3">

                            <button type ="submit" class="btn btn-danger">Confirmar</button>
                        </div>

        {% endblock contenido %}

Proyecto_final/producto/templates/producto/producto_categoria_create.html
{% extends 'tienda/base.html' %}
    {% block contenido %}
    <center>
    <h1> Categoria productos </h1>
    
    <h3>categoria:crear</h3>
    </center>
        <form method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit">Guardar</button>
            
        </form>
    {% endblock contenido %}

Proyecto_final/producto/templates/producto/producto_categoria_detalles.html
{% extends 'tienda/base.html' %}

{% block title  %}
    Detalle de Categoria de Productos
{% endblock title %}

        {% block contenido %}

            <h1>Detalle de Categoria de Productos</h1>
                <ul>
                    <li>{{ categoria.id }} 
                        {{ categoria.nombre }}
                        {{ categoria.descripcion }}
                    </li>        
                </ul>
         
        {% endblock contenido %}

Proyecto_final/producto/templates/producto/producto_categoria_list.html
{% extends 'tienda/base.html' %}

{% block title %}
    Categoria de Productos
{% endblock title %}

{% block contenido %}

    <h1>Categoria de Productos</h1>
    <div class="d-grid gap-4">
        <form action="{% url 'producto:productocategoria_list' %}" method="get">
            
            <input type="text" name="consulta" placeholder="Buscar....">
            
            <button type="submit" class="btn btn-primary">Buscar</button> <!-- Botón con color azul -->
        </form>
    </div>

    {% for object in object_list %}

    <ul>
 
        <li>{{object.nombre}}
        <div class="d-flex align-items-start"> <!-- Contenedor con clase d-flex para alinear los botones en la misma columna -->

        <div class="btn-group" role="group" aria-label="Botones de acción"> <!-- Contenedor para alinear los botones -->

        <a href="{% url 'producto:producto_categoria_detalles' object.id %}" class="btn btn-success me-2">Ver en detalle</a> <!-- Botón con color verde -->
        <a href="{% url 'producto:producto_categoria_update' object.id %}" class="btn btn-warning me-2">Editar</a> <!-- Botón con color amarillo -->
        <a href="{% url 'producto:producto_categoria_delete' object.id %}" class="btn btn-danger me-2">Eliminar</a> <!-- Botón con color rojo -->

        </li>

    </ul>

    {% endfor %}

{% endblock contenido %}