Proyecto_final/Proyecto_final/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("tienda.urls")),
    
    path('productos/', include("producto.urls")),
]

Proyecto_final/producto/urls.py
from django.urls import path

from .import views

app_name = "producto"

urlpatterns = [
   
    path('',views.index,name ="index"),
    
    #path('producto_categoria/list',views.producto_categoria_list,name ="producto_categoria_list"),
 
    path('productocategoria/list/',views.ProductoCategoriaList.as_view(),name ="productocategoria_list"),#las classes no se ejecutan de forma automatica  asi que agregamso el.as_view()
    
    path('productocategoria/create/', views.ProductoCategoriaCreate.as_view(), name="producto_categoria_create"),
    
    path('producto_categoria/detalles/<int:pk>/', views.ProductoCategoriaDetail.as_view(), name="producto_categoria_detalles"),
    path('producto_categoria/update/<int:pk>/', views.ProductoCategoriaUpdate.as_view(), name="producto_categoria_update"),
    path('producto_categoria/delete/<int:pk>/', views.ProductoCategoriaDelete.as_view(), name="producto_categoria_delete"),



]     

Proyecto_final/tienda/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from tienda import views
from .views import *
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
   
    path('',views.index,name ="index"),
    
    path('vendedor/list',views.vendedor_list,name='vendedor_list'),
    
    path('vendedor/creat',views.vendedor_creat,name='vendedor_creat'),
    
    path('eliminarVendedor/<vendedor_nombre>',views.eliminar_vendedor,name='EliminarVendedor'),
    
    
    
    path('comprador/list',views.comprador_list,name='comprador_list'),
    
    path('comprador/creat',views.comprador_creat,name='comprador_creat'),
    
    path('eliminarComprador/<comprador_nombre>',views.eliminar_comprador,name='EliminarComprador'),
    
    
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('about',about,name="about"),
    
    #crear producto
    
    path('crear_producto/',views.crear_producto,name="crear_producto"),
    
    #login , logout, registro
    
    path('login/', views.login_request, name='Login'),
    
    path('registro/', views.registro, name='Registro'),
    
    path ("logout/", LogoutView.as_view(template_name="tienda/logout.html"), name="logout"),  
   
]

Proyecto_final/tienda/models.py
from django.db import models
from django.contrib.auth.models import User

class Vendedor(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self) -> str:
        return f"{self.nombre},{self.apellido},{self.email}"

class Comprador(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self) -> str:
        return f"{self.nombre},{self.apellido},{self.email}"

class Producto(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='productos/')
    nombre = models.CharField(max_length=100)
    usado = models.BooleanField()
    descripcion = models.TextField()
    whatsapp = models.CharField(max_length=15)

    def __str__(self):
        return self.nombre

Proyecto_final/tienda/forms.py
from django import forms 
from. import models
from .models import Producto
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class VendedorForm(forms.ModelForm): 
    class Meta: 
        model = models.Vendedor
        fields = "__all__"
                
class CompradorForm(forms.ModelForm):   
    class Meta: 
        model = models.Comprador
        fields = "__all__"
          

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['imagen', 'nombre', 'usado', 'descripcion', 'whatsapp']
        

class CustomCreationForm(UserCreationForm):
    class Meta : 
        model = User
        fields = ['username', 'password1', 'password2']  
        widgets = {
            "username": forms.TextInput(attrs={"class":"form-control"}),
            "password1": forms.PasswordInput(attrs={"class":"form-control"}),
            "password2": forms.PasswordInput(attrs={"class":"form-control"}),
        }      
      

Proyecto_final/tienda/views.py
from django.shortcuts import render,redirect, get_object_or_404

from . import models,forms 

from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto
from .forms import ProductoForm , CustomCreationForm




def index(request):
     return render(request,"tienda/index.html")

def vendedor_list(request):
    consulta = models.Vendedor.objects.all() 
    contexto = {"vendedores": consulta} 
    return render (request, "tienda/vendedor_list.html", contexto) 


def vendedor_creat(request):
    if request.method =="POST":
        form =forms.VendedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("vendedor_list")
    else:
        form= forms.VendedorForm()    
    return render(request,"tienda/vendedor_creat.html",{"form":form})


def eliminar_vendedor(request,vendedor_nombre):
    vendedor = models.Vendedor.objects.get(nombre=vendedor_nombre)
    vendedor.delete()
    
    vendedores =models.Vendedor.objects.all() 
    contexto = {"vendedores":vendedores}
    return render (request, "tienda/vendedor_list.html",contexto)


#####################################

def comprador_list(request):
    consulta = models.Comprador.objects.all() 
    contexto = {"compradores": consulta} 
    return render (request, "tienda/comprador_list.html", contexto) 

def comprador_creat(request):
    if request.method =="POST":
        form =forms.CompradorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("comprador_list")
    else:
        form= forms.CompradorForm()    
    return render(request,"tienda/comprador_creat.html",{"form":form})

def eliminar_comprador(request,comprador_nombre):
    comprador = models.Comprador.objects.get(nombre=comprador_nombre)
    comprador.delete()
    
    compradores =models.Comprador.objects.all() 
    contexto = {"compradores":compradores}
    return render (request, "tienda/comprador_list.html",contexto)


class CustomLoginView(LoginView):
    template_name = 'tu_app/login.html'

class CustomLogoutView(LogoutView):
    template_name = 'tu_app/logout.html'
    
    
    
    
#login

def login_request(request):
    if request.method == "POST":   
            
        form= AuthenticationForm(request,data=request.POST)  
        if form.is_valid():   #Si paso la verificacion  
              
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password") 
            
            user = authenticate(username=usuario, password=contraseña)
            
            login(request, user) 
            
            return render (request, "tienda/index.html",{"mensaje":f'Bienvenido de nuevo {user.username}'})  # type: ignore
    else:
        form=AuthenticationForm()             
    return render(request,"tienda/login.html",{"form":form})


def registro(request):
    if request.method == "POST":
        form = CustomCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]  # Accede al nombre de usuario correctamente
            form.save()
            return render(request, "tienda/index.html", {"mensaje": "Usuario creado: "})
    else:
        form = CustomCreationForm()
    return render(request, "tienda/registro.html", {"form": form})



#  crear lista de about.html
def about(request):
    return render(request,"tienda/about.html")
    



# crear producto
def crear_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.usuario = request.user  # Asignar el usuario actual al producto
            producto.save()
            return redirect('tienda/index.html')  # Redirigir a la lista de productos después de guardar
    else:
        form = ProductoForm()
    return render(request, 'crear_producto.html', {'form': form})

 #   edicion de productos
 
 
def modificar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == "POST":
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.usuario = request.user
            producto.save()
            return redirect('detalle_producto', pk=producto.pk)
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'modificar_producto.html', {'form': form})

def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    producto.delete()
    return redirect('lista_productos')

Proyecto_final/tienda/templates/tienda/about.html
{% extends 'tienda/base.html' %}

{% block contenido %} 

    <div class=" display-1 mb-5 mt-3" style="font-family: monospace" >
        <h3>
           <h4>Mi_Primer_Entrega_Rafael_Ivan_Acevedo</h4> 
           <h4>Comision: 56060</h4>
           <h4>  </h4>
           <h4>Este proyecto fue realizado para el curso de Python de CoderHouse</h4>
           <h4>Creado por: Rafael Ivan Acevedo</h4>
                   
           <div class="d-flex">
            <h4>numero de contacto: </h4>
            <a class="btn btn-success ms-2" href="https:/wa.me/543815495052" target="_blank">WhatsApp</a> <!-- Botón de WhatsApp con margen a la izquierda -->
        </div>
         </h3>
        
    </div>
    <button><a href="{% url 'index' %}">Inicio</a></button>
{% endblock contenido %}

Proyecto_final/tienda/templates/tienda/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Tienda</title>
         
        {% block title %}
            
        {% endblock title %}


        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'tienda/assets/Favicon.ico' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'tienda/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        {% include 'tienda/navbar.html' %}
        <!-- Page Content-->
        
        <div class="container px-4 px-lg-5">

            {% block contenido %}
                
            {% endblock contenido %}

            {% include 'tienda/footer.html' %}
            
        

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'tienda/js/scripts.js' %}></script>
    </body>
</html>

Proyecto_final/tienda/templates/tienda/base2.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        {% block contenido %}
        
        {% endblock contenido %}

</body>
</html>

Proyecto_final/tienda/templates/tienda/comprador_creat.html
{% extends 'tienda/base.html' %}
    {% block contenido %}
    <center>
    <h1> Creacion de nuevo Comprador </h1>
    </center>
        <form method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit">Guardar</button>
            
        </form>
    {% endblock contenido %}

Proyecto_final/tienda/templates/tienda/comprador_list.html
{% extends 'tienda/base.html' %}

{% block contenido %}
<center>
<h1> Lista de Compradores</h1>
</center>
     <table border="1">
        <thead>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
        </thead>
        <tbody>
           {% for comprador in compradores  %}            
             <tr>
                  <td> {{ comprador.nombre }}</td> 
                  <td>  {{ comprador.apellido }} </td> 
                  <td> {{ comprador.email }} </td> 

                  <td>    <button>  
                    <a href="{% url 'EliminarComprador' comprador.nombre %}">Eliminar</a>
                          </button></td> 
             </tr>     
            {% endfor %}
        </tbody>
     </table>
   
{% endblock contenido %}

Proyecto_final/tienda/templates/tienda/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white"> &copy; mi sitio web 2023</p></div>
</footer>

Proyecto_final/tienda/templates/tienda/index.html
{% extends 'tienda/base.html' %}

{% load static %}

 {% block contenido %}

 <h1> Pagina principal</h1>
{% if mensaje %}
 
    {{mensaje}}
    
{% endif  %}

    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'tienda/imagen/mercado.jpg' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Ingrese al mercado o cree un nuevo usuario </h1>
          
            <div class="d-flex align-items-start"> 
             
                <div class="btn-group" role="group" aria-label="Botones de acción"></div>

                <li class="btn btn-primary me-2"><a class="nav-link {% if request.resolver_match.view_name == 'Login' %}active{% endif %}" href="{% url 'Login' %}">Inicio de sesión  </a></li>

                <li class="btn btn-warning me-2"><a class="nav-link {% if request.resolver_match.view_name == 'Registro' %}active{% endif %}" href="{% url 'Registro' %}">Registrar</li>
            </div>
           
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">bienvenido al sito de compra venta </p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        
        {% include 'tienda/tarjeta.html' with titulo="Tarjeta" texto="Texto de la tarjeta" %}
        {% include 'tienda/tarjeta.html' %}
        {% include 'tienda/tarjeta.html' %}
        {% include 'tienda/tarjeta.html' %}
        
    </div>
</div>
 {% endblock contenido %}
  

Proyecto_final/tienda/templates/tienda/login.html
{% extends 'tienda/base.html' %}
{% load static %} 
{% block contenido %}
    <h1>Login</h1>
    <form  method="POST">
        {% csrf_token %}
           {{form.as_p}}
         <button type="submit">Iniciar sesion</button>      
         <button type="submit">Volver</button>   
    </form> 
     
{% endblock contenido %}

Proyecto_final/tienda/templates/tienda/logout.html
{% extends 'tienda/base.html' %}

{% block title %}
    Logout
{% endblock title %}

{% block contenido %} 

    <div class="text-center display-1 mb-5 mt-3" style="font-family: monospace" >
        <h1>

            Has cerrado sesion

         </h1>
         
    </div>
    
    <button><a href="{% url 'index' %}">Inicio</a></button>
{% endblock contenido %}

Proyecto_final/tienda/templates/tienda/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                <li class="nav-item"><a class="nav-link {% if request.path == '/' %}active{% endif %} " aria-current="page" href="{% url 'index' %}">Inicio</a></li>                
                <li class="nav-item"><a class="nav-link {% if request.path == '/about' %}active{% endif %}" href="{% url 'about' %}"> Nosotros </a></li>

                {% if user.is_authenticated %}
                
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Panel de Administración</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/vendedor/creat' %}active{% endif %}"  href="{% url 'vendedor_creat' %}">formulario de vendedores </a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/vendedor/list' %}active{% endif %}"  href="{% url 'vendedor_list' %}">Lista de vendedores</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/productos/' %}active{% endif %}"  href="{% url 'producto:index' %}">Productos </a></li>
                <li class="nav-item">
                    
                    <form  action="{% url 'logout' %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-dark" >Cerrar sesión</button>
                    </form>
                    </li>

                {% endif %}
                 
            </ul>
        </div>
    </div>
</nav>

Proyecto_final/tienda/templates/tienda/registro.html
{% extends 'tienda/base.html' %}

{% load static  %}

{% block contenido %}

    <h1>Registro</h1>

    <form action="" method="POST">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Iniciar sesion</button>  
        <button type="submit">Guardar</button>

    </form>

{% endblock contenido %}

Proyecto_final/tienda/templates/tienda/tarjeta.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{titulo}}</h2>
            <p class="card-text">{{texto}}</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!"> Ver </a></div>
    </div>
</div>

Proyecto_final/tienda/templates/tienda/vendedor_creat.html
{% extends 'tienda/base.html' %}
    {% block contenido %}
    <center>
    <h1> Creacion de nuevo Vendedor </h1>
    </center>
        <form method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit">Guardar</button>
            
        </form>
    {% endblock contenido %}

Proyecto_final/tienda/templates/tienda/vendedor_list.html
{% extends 'tienda/base.html' %}

{% block contenido %}

<center>
    <h1> Lista de Vendedores</h1>
 </center>
        <table border="1">
            <thead>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
            </thead>
            <tbody>
                {% for vendedor in vendedores  %}  
                    <tr>                     
                      <td>  {{ vendedor.nombre }}</td> 
                      <td> {{ vendedor.apellido }} </td> 
                       <td> {{ vendedor.email }}</td> 
                       <td>    <button>  
                                <a href="{% url 'EliminarVendedor' vendedor.nombre %}">Eliminar</a>
                            </button></td> 
                    </tr> 
                {% endfor %}
            </tbody>
        </table>
    
{% endblock contenido %}